; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32c3
build_dir = /tmp/pio-homeio-esp32-build

[env:esp32c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = partitions_ota_large.csv
board_build.filesystem = littlefs
build_flags =
    -include include/esp32c3_sleep_compat.h
    -DHOMIE_CONVENTION_VERSION=5
    -DHOMIE_STRICT_PROPERTY_VALIDATION=1
    -DHOMIE_USE_LITTLEFS=1
lib_compat_mode = strict
lib_deps =
    file://lib/homie-v5-local
    https://github.com/stangsdal/modbus-core.git
    https://github.com/stangsdal/modbus-device-ahc9000.git
