; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32c3

[env:esp32c3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
board_build.partitions = partitions_ota_large.csv
build_flags =
	-include include/esp32c3_sleep_compat.h
lib_compat_mode = strict
lib_deps = 
	labodj/homie-v5 @ ^3.6.1
	https://github.com/stangsdal/modbus-core.git
	https://github.com/stangsdal/modbus-device-ahc9000.git
	knolleary/PubSubClient@^2.8.0
